# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c67aff5bd1a5746207d4533cfd910f1c00741aa7f1bfbf088a9c09102a9a608fec5da47e4cec1824de8e8139bd47487340025ebbb3373da653a80b7953df573b

test:
  secret_key_base: 4da4f9797ae8cbf1c9ec695d7f266cc244637a9434231fe14b49f032851575a7b6b7f130ee3d3eca84dfd11fdf08ec649a8d4be4c5bc5de71b512ac1b1a7774d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
